language: python
python:
 - "3.6.4"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest-cov

before script:
  - psql -c 'create database fastfoodfast:' -U postgress
  - psql -c 'create database fastfoodfast_test:' -U postgress
  
script: 
  - pytest --cov=tests


after_success:
  - coveralls

  

   